services:
  payment-api:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: change_me_en_dev
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

volumes:
  dbdata: