name: CI/CD Payment API

on:
  push:
    branches:
      - "**"

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Lancer les tests
        run: pytest -q

  build:
    needs: test

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: |
          docker build -t payment-api .

  deploy:
    needs: build

    if: github.ref == 'refs/heads/main'

    environment: production

    runs-on: ubuntu-latest

    steps:
      - name: Déploiement
        run: |
          echo "Déploiement en production"